### PR TITLE
docs(deploy): make authorizer logic more clear

### PR DESCRIPTION
**Pull request by mmalenic**
### Changes

* Update wording and naming slightly to make it clear that a JWT authorizer is being used.

### CODE REVIEW

**Review by brainstorm — CHANGES_REQUESTED** [review]
https://github.com/umccr/htsget-rs/actions/runs/7924478956/job/21636099139?pr=224#step:7:699

Probably a good time to add https://github.com/MarcoIeni/cargo-assist to CI to avoid those? :)

**Comment by mmalenic** [comment]
I feel like automatically changing the code without input doesn't sound like a great idea? Although, I guess clippy and fmt wouldn't do anything destructive? 

I tried to address this by adding clippy and fmt to the pre-commit config, although I think this is a new lint, and my Rust installation wasn't up to date.

**Review by brainstorm — APPROVED** [review]
I suspect that `cargo-assist` helps more than annoy, since we've had a few PR where we totally forgot about `fmt` and `clippy`, but I hear you about code being changed automatically... let's leave it as-is then for now, I might experiment in other projects and come back to it to this repo if it works well.

**Comment by mmalenic** [comment]
Sure. We can make another PR for it if we want. I'm not totally against it, we have other automation which makes commits and changes code, e.g. deployment or dependabot.

It could potentially be annoying if it changes the code on the working branch, and then you make another commit but the push gets rejected because of an out of date local branch. Although, I suspect this wouldn't happen that often because it only runs on a pull request.

**Pull request merged**
