### PR TITLE
Add BCF support

### LINKED ISSUE #33: Implement BCF search backend (/variants endpoint)
Since Noodles finished up its support relatively recently, its up for grabs:

https://github.com/zaeleus/noodles/issues/13

lower priority than the other formats and tasks though, since it's not used as much as `.vcf.gz`, but it would be great to have anyway for completeness and in-spec.

### PR DESCRIPTION
**Pull request by CastilloDel**
Closes #33

### CODE REVIEW

**Comment by CastilloDel** [comment]
This is ready for review now! It adds support for the BCF format with the `.bcf.gz` extension and with CSI indexes.

**Review by brainstorm — APPROVED** [review]
Thanks @CastilloDel, this looks really good, similar to the VCF impl but with some gotchas, well done!

@mmalenic Would you like to review Daniel's code a bit and comment? :)

**Comment by mmalenic** [comment]
Looks great to me! Really well done :)

I can see some clear common code across all the formats. 
We can refactor this later, however some of it might need some thought.

**Comment by brainstorm** [comment]
Thanks Marko for taking a look, @CastilloDel feel free to squash and merge, LGTM!

**Comment by zaeleus** [comment]
> It adds support for the BCF format with the `.bcf.gz` extension and with CSI indexes.

Note that the extension for a BCF file is simply `.bcf`. Like BAM, it is inherently BGZF-compressed.

**Comment by brainstorm** [comment]
> > It adds support for the BCF format with the `.bcf.gz` extension and with CSI indexes.
> 
> Note that the extension for a BCF file is simply `.bcf`. Like BAM, it is inherently BGZF-compressed.

True! I noted that on the #htsget-lsg GA4GH Slack channel, @CastilloDel, can you please address this right before merging? Thanks @zaeleus for the catch!

**Comment by CastilloDel** [comment]
Yes, that was already on my list! I'm on it now!

**Pull request merged**
