### PR TITLE
build: update Cargo.lock

### PR DESCRIPTION
**Pull request by mmalenic**
This should've been part of https://github.com/umccr/htsget-rs/pull/185.

### Changes
* Update `Cargo.lock`.

### CODE REVIEW

**Review by brainstorm — CHANGES_REQUESTED** [review]
There are a couple of clippy failures in `resolver.rs` and `types.rs` which will most probably trip up next CI run, better fix them on this PR?

**Comment by mmalenic** [comment]
Yes, it's the new clippy lints, e.g. `clippy::let_with_type_underscore`.

**Comment by brainstorm** [comment]
> Yes, it's the new clippy lints, e.g. `clippy::let_with_type_underscore`.

Oh, thx, keep forgetting about it: https://twitter.com/braincode/status/1653997437097484288 ... issue got fixed 2 weeks ago, btw, so it should be solved in stable soonish, I guess.

**Comment by mmalenic** [comment]
It seems to be resolved in nightly, let me see if it is resolved in stable.

**Review by brainstorm — APPROVED** [review]
👏🏻

**Pull request merged**
